### ISSUE TITLE
Acquire Clamity Anarchy backup

### ISSUE THREAD

**Issue by erlehmann** [OysterityAnarchy/minetest#1]
## Problem

Clamity servers are gone.

**Comment by erlehmann** [comment]
@StrychtenOfClamity if you do no longer want to run clamity, please could you give @corarona or someone else that can be trusted to not abuse it a backup of the clamity folder so they can bring back the server world on their own terms?

I am really sad right now, as Clamity was something special. A lot of people from the community put work into building things. I met people there who were really nice and built bases with my friends that I would like to visit again.

**Comment by anon55555** [comment]
@StrychtenOfClamity I've heard that Edgy1 will transfer the server to @corarona with your approval, do you approve?

**Comment by corarona** [comment]
can't fix :(
